name: moe.deep_linear_network
_target_: src.model.${model.name}.Model
_convert_: none
_recursive_: False
model_cfg:
  num_layers: 1
  hidden_size: 512
  dataset_name: ${dataloader.name}
  classifier:
    should_freeze: False
    should_share: True
loss_fn_cfg: ${loss}
