defaults:
  - setup: base
  - dataloader: mnist
  - experiment: four_path_model
  - model: four_path_model
  - logbook: xplogger
  - optimizer: adam
  - notifier: zulip
  - override hydra/launcher: submitit_slurm
  - _self_
  # - override hydra/launcher: submitit_local

hydra:
  job_logging:
    root:
      handlers: []
  run:
    dir: outputs/${setup.id}/${now:%Y-%m-%d_%H-%M-%S}

  launcher:
    timeout_min: 59
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 64
    nodes: 1
    # name: ${setup.id}
    submitit_folder: /private/home/sodhani/projects/dln/logs/submitit/%j
    partition: learnlab # learnlab prioritylab, devlab
    signal_delay_s: 120
    max_num_timeout: 3
    # constraint: volta32gb
    # additional_parameters:
      # open-mode: append
    # comment: neurips deadline
