PYTORCH_JIT=0 python3 -u main.py \
setup.seed=1 \
setup.base_path=/fsx-labs/sodhani/projects/abstraction_by_gating \
setup.slurm.cloud=aws \
dataloader=mnist \
dataloader.train_config.dataloader.batch_size=8 \
experiment=k_path \
experiment.num_epochs=1000 \
experiment.task.num_input_transformations=40 \
experiment.task.num_classes_in_selected_dataset=10 \
experiment.task.mode=permute_input_permute_target \
model.decoder_cfg.should_share=False \
model.encoder_cfg.should_share=False \
model.gate_cfg.mode=5_plus_mod_permute \
model.hidden_layer_cfg.dim=128 \
model.hidden_layer_cfg.should_share=True \
model.hidden_layer_cfg.should_use_non_linearity=False \
model.hidden_layer_cfg.num_layers=1 \
model.pretrained_cfg.should_use=False \
model.should_use_non_linearity=False \
model.weight_init.should_do=True \
model.weight_init.gain=10.0 \
model.weight_init.bias=0 \
optimizer=sgd \
optimizer.lr=0.0001 \
optimizer.momentum=0.9