name: cifar10
_target_: src.data.cifar10.dataloader.build_dataloaders
_recursive_: False
train_config:
  dataset:
    root: ${setup.base_path}/data/cifar10
    train: True
    download: True
  dataloader:
    batch_size: 128
    shuffle: True
    num_workers: 6
    pin_memory: True
test_config:
  dataset:
    root: ${setup.base_path}/data/cifar10
    train: False
  dataloader:
    batch_size: 256
    shuffle: False
    num_workers: 6
    pin_memory: True
is_preprocessed: False